### PR TITLE
all squads 15/16

### PR DESCRIPTION
**Pull request by alex-ruehe**
squads for bundesliga 15/16 - based on kicker.de data

### CODE REVIEW

**Comment by geraldb** [comment]
Wow. Great. Thanks for your efforts. Was just getting started on the script.

**Comment by geraldb** [comment]
PS: Some notes on the format. No worries will try to reformat with a script. Let's use as an example:

```
(25)    Nagasawa, Kazuki                MF  2014    16.12.1991  JPN
(1) Horn, Timo                      GK  2002    12.05.1993  GER
(19)    Mavraj, Mergim                  DF  2014    09.06.1986  ALB
```

The squad reader no longer needs brackets for the number e.g.

```
25  Nagasawa, Kazuki                MF  2014    16.12.1991  JPN
1       Horn, Timo                      GK  2002    12.05.1993  GER
19          Mavraj, Mergim                  DF  2014    09.06.1986  ALB
```

The date of birth should be a comment (let's leave it for now - might be good to have it "inline". The idea is the player is just a reference here and there's actually a player database/dataset (see [/players](https://github.com/openfootball/players)) with all details e.g. date of birth, place of birth, alternative names, etc. 

Final step would be some kind of pretty printing e.g. sort by position e.g. first all GK - goalkeeper, next defenders, etc.  Mini optimize - no nationality needed for "natives" e.g. GER for Bundesliga, thus leading to (preferred):

```
1       Horn, Timo                                     GK   2002
19          Mavraj, Mergim       (ALB)              DF  2014        
25  Nagasawa, Kazuki  (JPN)                MF   2014
```

or

```
1       Horn, Timo                      GK  2002        GER        # 12.05.1993
19          Mavraj, Mergim                  DF  2014    ALB         # 09.06.1986
25  Nagasawa, Kazuki                MF  2014    JPN         # 16.12.1991
```

No worries. All just getting started. Thanks again. Cheers.

**Comment by alex-ruehe** [comment]
I'm trying to fix that - shouldn't be to hard to match your format. The sorting mess is my fault, should've used python lists instead of dicts - I'm trying to fix that as well.

**Comment by geraldb** [comment]
@alexrockt No worries. I actually prefer the json format for importing. That was a great idea. The reformatter (pretty printer) can get reused (for future imports etc.)  

Thus, would be great if you can please (just) update the json file. Do NOT worry about the plain text format. As far as I can see the contract year (playing since is missing) is missing in the "old" json file.. Keep it up. Great stuff. Thanks again.

**Pull request merged**
