### PR TITLE
more data

### PR DESCRIPTION
**Pull request by A-A-G**
Found another missing header and a few typos and added some more game data from http://www.football-data.co.uk/germanym.php.

### CODE REVIEW

**Comment by geraldb** [comment]
@A-A-G   +1 for fixing header added and +1 typos fixed

Sorry adding more game data is more complicated if you're new - for automated match data there's already the fooball.csv/deutschland repo -> https://github.com/footballcsv/deutschland   if you do NOT edit the match data by hand (as you do), please add the data to the football.csv repo - the go together (one works like a wiki and the other is "automated" easy to machine read and write match data)...  PS: I try to add your first commit if I can figure out how.  Keep it up. Thanks for contributions. Cheers. Prost.

**Review by geraldb — APPROVED** [review]

**Review by geraldb — COMMENTED** [review]
Thanks for the typo fixes. NOTE: VfL Osnabrück is NOT a type it is the correct spelling. Also nothing wrong with Spvgg Großaspach as far as I can tell (will double check).  If an alternate club name is missing - the right way is NOT to change the match data but the clubs data : - ), see https://github.com/openfootball/clubs/blob/master/europe/germany/de.clubs.txt    Thanks for your contributions. Keep it up. Cheers. Prost.

**Update** Thanks again. I double check VfL Osnabrück is the correct spelling and should work, see https://github.com/openfootball/clubs/blob/master/europe/germany/de.clubs.txt#L133  Sorry, yes Großaspach was a typo (and fixed) to follow all other name entries.

**Review by geraldb — CHANGES_REQUESTED** [review]
Sorry for now please add new (auto-generated) match data to the football.csv repos. See https://github.com/footballcsv/deutschland

**Comment by A-A-G** [comment]
> Thanks for the typo fixes. NOTE: VfL Osnabrück is NOT a type it is the correct spelling. Also nothing wrong with Spvgg Großaspach as far as I can tell (will double check). If an alternate club name is missing - the right way is NOT to change the match data but the clubs data : - ), see https://github.com/openfootball/clubs/blob/master/europe/germany/de.clubs.txt Thanks for your contributions. Keep it up. Cheers. Prost.

Ok, i cannot check it now but i had the impression, that if club names do not match inside a file sportdb complains about it. Also, i have no idea of how i can change the club list for testing.

**Comment by geraldb** [comment]
Sorry I was three days on vacation (and stop to finish the /deutschland format conversion with the season 2016-17 and 2017-18 missing).  I try to get it done today (Dec/14).

You can use the latest clubs version (instead of the bundled-up / packaged version) by getting a (local) copy of https://github.com/openfootball/clubs and than using a custom ruby script (configuration) code e.g.:

     # use (switch to) "external" datasets  (instead of pre-packaged / bundled-up version)
     SportDb::Import.config.clubs_dir   = "../clubs"

I try to put together a new footballdb-clubs bundle (gem) in the next days too so that they are in sync again for the /deutschland update.  Again thanks the patience and keeping up. Cheers.

**Comment by geraldb** [comment]
FYI:   Thanks again. I added your typos and fixes "by hand" and cleaned-up the missing 2016/17 and 2017/18 season for the new format changes. Everything should be working (building) now for the /deutschland repo.  PS: I will try a test build tomorrow (Dec/15) as I don't have access to the sportdb tool today.  Cheers. Prost.

**Comment by A-A-G** [comment]
fails at the same position as before:
*** error: SQLite3::ConstraintException: UNIQUE constraint failed: events_teams.event_id, events_teams.team_id

**Comment by geraldb** [comment]
> *** error: SQLite3::ConstraintException: UNIQUE constraint failed: events_teams.event_id, events_teams.team_id

Thanks for trying and reporting the error. Sorry for the trouble.  I can't run any code today (Dec/14). I will fix it tomorrow (Dec/15) . Thanks for the patience. Cheers. Greetings from Vienna, Austria.

**Comment by A-A-G** [comment]
> > *** error: SQLite3::ConstraintException: UNIQUE constraint failed: events_teams.event_id, events_teams.team_id
> 
> Thanks for trying and reporting the error. Sorry for the trouble. I can't run any code today (Dec/14). I will fix it tomorrow (Dec/15) . Thanks for the patience. Cheers. Greetings from Vienna, Austria.

You're welcome. I was just trying to help and leave some feedback. I had the feeling that there will be a problem if the team name are not unique. May be an update of the club list will fix this?
Anyway, my de-database is ready now. No hurry. :)

I would like to build a national team database in addition, but there seems to be even more problems...

**Comment by geraldb** [comment]
Thanks for your help. Greatly appreciated.

> I had the feeling that there will be a problem if the team name are not unique. May be an update of the club list will fix this?

The "new" design is that alternate club names (and even conflicting) names should work without any trouble  (yes, as long as the alternate name is in the club list, see https://github.com/openfootball/clubs ).

> I would like to build a national team database in addition, but there seems to be even more
> problems...

Sorry, the national team parser / setup is currently broken - I'm trying to make the setup and format easier and working my way through, that is, for now I'm getting the clubs back online with the new format - next is the int'l club competitions (e.g. champions leagues, etc.) and than back to the national teams (likely in January). Thanks for the patience.

**Comment by geraldb** [comment]
Sorry, yes you're are / were right VfL Osnabrück (9x) and Vfl Osnabrück (5x) in the auto config are NOT unique and result in the SQL UNIQUE constraint error. The easy fix is yours and applied. Thanks. 

I'm closing the pull request - all  missing headings and typos fixed / applied "by hand". Thanks again.  For adding new (old) seasons (if still interested), please start at the football.csv org / repos - https://github.com/footballcsv/deutschland    Cheers. Prost.

**Pull request closed without merging**
